In [1]:
import essentia.standard as ess
import numpy as np
from scipy import pi
l= 22
inputArray = [1, 1, 0, 0, 1]
outputSize = 4
inputSize = 5
dct2 = ess.DCT(inputSize=len(inputArray), 
                outputSize=outputSize, 
                dctType = 2, 
                liftering = 0)(inputArray)

dct3 = ess.DCT(inputSize=len(inputArray), 
                outputSize=outputSize, 
                dctType = 3, 
                liftering = l)(inputArray)

print ess.DCT(inputSize=len(inputArray), 
                outputSize=outputSize, 
                dctType = 3, 
                liftering = 0)(inputArray)

dct3NoLiftering = dct3
N = len(dct3NoLiftering)
for i in range(N):
    dct3NoLiftering[i] /= 1 + l * np.sin(pi*i/l) / 2



[ 1.89736652  0.37174797  0.82789505 -0.60150111]


In [21]:
dct = ess.DCT(inputSize=5, 
                outputSize=4, 
                dctType = 3, 
                liftering = 22)

idct = ess.IDCT(inputSize=4, 
                outputSize=5, 
                dctType = 3, 
                liftering = 22)

print dct([ 1, 1, 0, 0, 1 ])

[ 1.89736652  0.95370573  3.39358997 -3.35009956]


In [3]:
mfccSize= 4
freqSize= 5
dctTable = np.zeros([freqSize, mfccSize])

scaleDefault = np.sqrt(2.0/freqSize)
for i in range(mfccSize):
    if i == 0:
        scale = scaleDefault/2
    else:
        scale = scaleDefault
    for j in range(freqSize):
        freqMultiplier = pi / inputSize * i;
        dctTable[j][i] =  (scale * np.cos( freqMultiplier * ( j + 0.5) ))  
print dctTable.shape
dctTable = dctTable
inversedDCT = np.zeros(freqSize)
for i in range(freqSize):
    inversedDCT[i] = 0.0
    for j in range(mfccSize):
        inversedDCT[i] += dct3NoLiftering[j] * dctTable[i][j];    

print dctTable
print inversedDCT

(5, 4)
[[  3.16227766e-01   6.01500955e-01   5.11667274e-01   3.71748034e-01]
 [  3.16227766e-01   3.71748034e-01  -1.95439508e-01  -6.01500955e-01]
 [  3.16227766e-01   3.87267321e-17  -6.32455532e-01  -1.16180196e-16]
 [  3.16227766e-01  -3.71748034e-01  -1.95439508e-01   6.01500955e-01]
 [  3.16227766e-01  -6.01500955e-01   5.11667274e-01  -3.71748034e-01]]
[ 1.02360668  0.93819664  0.07639318 -0.06180349  1.02360687]


In [4]:
mfccSize= 4
freqSize= 5
dctTable = np.zeros([freqSize, mfccSize])

scaleDefault = np.sqrt(2.0/freqSize)
for i in range(mfccSize):
    if i == 0:
        scale = scaleDefault/np.sqrt(2)
    else:
        scale = scaleDefault
    for j in range(freqSize):
        freqMultiplier = pi / inputSize * i;
        dctTable[j][i] =  (scale * np.cos( freqMultiplier * ( j + 0.5) ))  
print dctTable.shape
dctTable = dctTable
inversedDCT = np.zeros(freqSize)
for i in range(freqSize):
    inversedDCT[i] = 0.0
    for j in range(mfccSize):
        inversedDCT[i] += dct2[j] * dctTable[i][j];    

print dctTable
print inversedDCT

(5, 4)
[[  4.47213595e-01   6.01500955e-01   5.11667274e-01   3.71748034e-01]
 [  4.47213595e-01   3.71748034e-01  -1.95439508e-01  -6.01500955e-01]
 [  4.47213595e-01   3.87267321e-17  -6.32455532e-01  -1.16180196e-16]
 [  4.47213595e-01  -3.71748034e-01  -1.95439508e-01   6.01500955e-01]
 [  4.47213595e-01  -6.01500955e-01   5.11667274e-01  -3.71748034e-01]]
[ 1.02360667  0.93819663  0.07639316 -0.0618035   1.02360686]
